/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as ProtectedPosRouteImport } from './routes/_protected.pos'
import { Route as ProtectedKelolaoutletRouteImport } from './routes/_protected.kelolaoutlet'
import { Route as ProtectedKelolagudangRouteImport } from './routes/_protected.kelolagudang'
import { Route as ProtectedForbiddenRouteImport } from './routes/_protected.forbidden'
import { Route as ProtectedManagementRouteImport } from './routes/_protected._management'
import { Route as ProtectedInventory_groupRouteImport } from './routes/_protected._inventory_group'
import { Route as ProtectedManagementUsersRouteImport } from './routes/_protected._management.users'
import { Route as ProtectedManagementSuppliersRouteImport } from './routes/_protected._management.suppliers'
import { Route as ProtectedManagementRolesRouteImport } from './routes/_protected._management.roles'
import { Route as ProtectedManagementProductsRouteImport } from './routes/_protected._management.products'
import { Route as ProtectedManagementProductAttributesRouteImport } from './routes/_protected._management.product-attributes'
import { Route as ProtectedManagementOutletandgudangRouteImport } from './routes/_protected._management.outletandgudang'
import { Route as ProtectedInventory_groupMarketsRouteImport } from './routes/_protected._inventory_group.markets'
import { Route as ProtectedInventory_groupInventoryStockRouteImport } from './routes/_protected._inventory_group.inventory-stock'
import { Route as ProtectedInventory_groupInventoryOpsRouteImport } from './routes/_protected._inventory_group.inventory-ops'
import { Route as ProtectedInventory_groupInventoryRouteImport } from './routes/_protected._inventory_group.inventory'
import { Route as ProtectedInventory_groupInventoryIndexRouteImport } from './routes/_protected._inventory_group.inventory.index'
import { Route as ProtectedInventory_groupInventoryRejectRequestsRouteImport } from './routes/_protected._inventory_group.inventory.reject-requests'

const DesignLazyRouteImport = createFileRoute('/design')()
const GuestIndexLazyRouteImport = createFileRoute('/_guest/')()
const ProtectedTransactionsLazyRouteImport = createFileRoute(
  '/_protected/transactions',
)()
const ProtectedTestRemoteSerialLazyRouteImport = createFileRoute(
  '/_protected/test-remote-serial',
)()
const ProtectedSettingsLazyRouteImport = createFileRoute(
  '/_protected/settings',
)()
const ProtectedDataTransaksiLazyRouteImport = createFileRoute(
  '/_protected/data-transaksi',
)()
const ProtectedDashboardLazyRouteImport = createFileRoute(
  '/_protected/dashboard',
)()
const ProtectedKelolaoutletTransfersLazyRouteImport = createFileRoute(
  '/_protected/kelolaoutlet/transfers',
)()
const ProtectedKelolaoutletStockLazyRouteImport = createFileRoute(
  '/_protected/kelolaoutlet/stock',
)()
const ProtectedKelolaoutletRejectsLazyRouteImport = createFileRoute(
  '/_protected/kelolaoutlet/rejects',
)()
const ProtectedKelolaoutletReceiveLazyRouteImport = createFileRoute(
  '/_protected/kelolaoutlet/receive',
)()
const ProtectedKelolagudangTransfersLazyRouteImport = createFileRoute(
  '/_protected/kelolagudang/transfers',
)()
const ProtectedKelolagudangStockLazyRouteImport = createFileRoute(
  '/_protected/kelolagudang/stock',
)()
const ProtectedKelolagudangRejectsLazyRouteImport = createFileRoute(
  '/_protected/kelolagudang/rejects',
)()
const ProtectedKelolagudangReceiveLazyRouteImport = createFileRoute(
  '/_protected/kelolagudang/receive',
)()
const ProtectedKelolagudangPurchasesLazyRouteImport = createFileRoute(
  '/_protected/kelolagudang/purchases',
)()
const ProtectedManagementReportItemLazyRouteImport = createFileRoute(
  '/_protected/_management/report-item',
)()
const ProtectedInventory_groupStockOpnameLazyRouteImport = createFileRoute(
  '/_protected/_inventory_group/stock-opname',
)()
const ProtectedInventory_groupStockManagementLazyRouteImport = createFileRoute(
  '/_protected/_inventory_group/stock-management',
)()
const ProtectedInventory_groupInventoryDashboardLazyRouteImport =
  createFileRoute('/_protected/_inventory_group/inventory-dashboard')()

const DesignLazyRoute = DesignLazyRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/design.lazy').then((d) => d.Route))
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestIndexLazyRoute = GuestIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuestRoute,
} as any).lazy(() => import('./routes/_guest.index.lazy').then((d) => d.Route))
const ProtectedTransactionsLazyRoute =
  ProtectedTransactionsLazyRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => ProtectedRoute,
  } as any).lazy(() =>
    import('./routes/_protected.transactions.lazy').then((d) => d.Route),
  )
const ProtectedTestRemoteSerialLazyRoute =
  ProtectedTestRemoteSerialLazyRouteImport.update({
    id: '/test-remote-serial',
    path: '/test-remote-serial',
    getParentRoute: () => ProtectedRoute,
  } as any).lazy(() =>
    import('./routes/_protected.test-remote-serial.lazy').then((d) => d.Route),
  )
const ProtectedSettingsLazyRoute = ProtectedSettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any).lazy(() =>
  import('./routes/_protected.settings.lazy').then((d) => d.Route),
)
const ProtectedDataTransaksiLazyRoute =
  ProtectedDataTransaksiLazyRouteImport.update({
    id: '/data-transaksi',
    path: '/data-transaksi',
    getParentRoute: () => ProtectedRoute,
  } as any).lazy(() =>
    import('./routes/_protected.data-transaksi.lazy').then((d) => d.Route),
  )
const ProtectedDashboardLazyRoute = ProtectedDashboardLazyRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any).lazy(() =>
  import('./routes/_protected.dashboard.lazy').then((d) => d.Route),
)
const ProtectedPosRoute = ProtectedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => ProtectedRoute,
} as any).lazy(() =>
  import('./routes/_protected.pos.lazy').then((d) => d.Route),
)
const ProtectedKelolaoutletRoute = ProtectedKelolaoutletRouteImport.update({
  id: '/kelolaoutlet',
  path: '/kelolaoutlet',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedKelolagudangRoute = ProtectedKelolagudangRouteImport.update({
  id: '/kelolagudang',
  path: '/kelolagudang',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedForbiddenRoute = ProtectedForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedManagementRoute = ProtectedManagementRouteImport.update({
  id: '/_management',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedInventory_groupRoute =
  ProtectedInventory_groupRouteImport.update({
    id: '/_inventory_group',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedKelolaoutletTransfersLazyRoute =
  ProtectedKelolaoutletTransfersLazyRouteImport.update({
    id: '/transfers',
    path: '/transfers',
    getParentRoute: () => ProtectedKelolaoutletRoute,
  } as any).lazy(() =>
    import('./routes/_protected.kelolaoutlet.transfers.lazy').then(
      (d) => d.Route,
    ),
  )
const ProtectedKelolaoutletStockLazyRoute =
  ProtectedKelolaoutletStockLazyRouteImport.update({
    id: '/stock',
    path: '/stock',
    getParentRoute: () => ProtectedKelolaoutletRoute,
  } as any).lazy(() =>
    import('./routes/_protected.kelolaoutlet.stock.lazy').then((d) => d.Route),
  )
const ProtectedKelolaoutletRejectsLazyRoute =
  ProtectedKelolaoutletRejectsLazyRouteImport.update({
    id: '/rejects',
    path: '/rejects',
    getParentRoute: () => ProtectedKelolaoutletRoute,
  } as any).lazy(() =>
    import('./routes/_protected.kelolaoutlet.rejects.lazy').then(
      (d) => d.Route,
    ),
  )
const ProtectedKelolaoutletReceiveLazyRoute =
  ProtectedKelolaoutletReceiveLazyRouteImport.update({
    id: '/receive',
    path: '/receive',
    getParentRoute: () => ProtectedKelolaoutletRoute,
  } as any).lazy(() =>
    import('./routes/_protected.kelolaoutlet.receive.lazy').then(
      (d) => d.Route,
    ),
  )
const ProtectedKelolagudangTransfersLazyRoute =
  ProtectedKelolagudangTransfersLazyRouteImport.update({
    id: '/transfers',
    path: '/transfers',
    getParentRoute: () => ProtectedKelolagudangRoute,
  } as any).lazy(() =>
    import('./routes/_protected.kelolagudang.transfers.lazy').then(
      (d) => d.Route,
    ),
  )
const ProtectedKelolagudangStockLazyRoute =
  ProtectedKelolagudangStockLazyRouteImport.update({
    id: '/stock',
    path: '/stock',
    getParentRoute: () => ProtectedKelolagudangRoute,
  } as any).lazy(() =>
    import('./routes/_protected.kelolagudang.stock.lazy').then((d) => d.Route),
  )
const ProtectedKelolagudangRejectsLazyRoute =
  ProtectedKelolagudangRejectsLazyRouteImport.update({
    id: '/rejects',
    path: '/rejects',
    getParentRoute: () => ProtectedKelolagudangRoute,
  } as any).lazy(() =>
    import('./routes/_protected.kelolagudang.rejects.lazy').then(
      (d) => d.Route,
    ),
  )
const ProtectedKelolagudangReceiveLazyRoute =
  ProtectedKelolagudangReceiveLazyRouteImport.update({
    id: '/receive',
    path: '/receive',
    getParentRoute: () => ProtectedKelolagudangRoute,
  } as any).lazy(() =>
    import('./routes/_protected.kelolagudang.receive.lazy').then(
      (d) => d.Route,
    ),
  )
const ProtectedKelolagudangPurchasesLazyRoute =
  ProtectedKelolagudangPurchasesLazyRouteImport.update({
    id: '/purchases',
    path: '/purchases',
    getParentRoute: () => ProtectedKelolagudangRoute,
  } as any).lazy(() =>
    import('./routes/_protected.kelolagudang.purchases.lazy').then(
      (d) => d.Route,
    ),
  )
const ProtectedManagementReportItemLazyRoute =
  ProtectedManagementReportItemLazyRouteImport.update({
    id: '/report-item',
    path: '/report-item',
    getParentRoute: () => ProtectedManagementRoute,
  } as any).lazy(() =>
    import('./routes/_protected._management.report-item.lazy').then(
      (d) => d.Route,
    ),
  )
const ProtectedInventory_groupStockOpnameLazyRoute =
  ProtectedInventory_groupStockOpnameLazyRouteImport.update({
    id: '/stock-opname',
    path: '/stock-opname',
    getParentRoute: () => ProtectedInventory_groupRoute,
  } as any).lazy(() =>
    import('./routes/_protected._inventory_group.stock-opname.lazy').then(
      (d) => d.Route,
    ),
  )
const ProtectedInventory_groupStockManagementLazyRoute =
  ProtectedInventory_groupStockManagementLazyRouteImport.update({
    id: '/stock-management',
    path: '/stock-management',
    getParentRoute: () => ProtectedInventory_groupRoute,
  } as any).lazy(() =>
    import('./routes/_protected._inventory_group.stock-management.lazy').then(
      (d) => d.Route,
    ),
  )
const ProtectedInventory_groupInventoryDashboardLazyRoute =
  ProtectedInventory_groupInventoryDashboardLazyRouteImport.update({
    id: '/inventory-dashboard',
    path: '/inventory-dashboard',
    getParentRoute: () => ProtectedInventory_groupRoute,
  } as any).lazy(() =>
    import('./routes/_protected._inventory_group.inventory-dashboard.lazy').then(
      (d) => d.Route,
    ),
  )
const ProtectedManagementUsersRoute =
  ProtectedManagementUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => ProtectedManagementRoute,
  } as any).lazy(() =>
    import('./routes/_protected._management.users.lazy').then((d) => d.Route),
  )
const ProtectedManagementSuppliersRoute =
  ProtectedManagementSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => ProtectedManagementRoute,
  } as any).lazy(() =>
    import('./routes/_protected._management.suppliers.lazy').then(
      (d) => d.Route,
    ),
  )
const ProtectedManagementRolesRoute =
  ProtectedManagementRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => ProtectedManagementRoute,
  } as any).lazy(() =>
    import('./routes/_protected._management.roles.lazy').then((d) => d.Route),
  )
const ProtectedManagementProductsRoute =
  ProtectedManagementProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => ProtectedManagementRoute,
  } as any).lazy(() =>
    import('./routes/_protected._management.products.lazy').then(
      (d) => d.Route,
    ),
  )
const ProtectedManagementProductAttributesRoute =
  ProtectedManagementProductAttributesRouteImport.update({
    id: '/product-attributes',
    path: '/product-attributes',
    getParentRoute: () => ProtectedManagementRoute,
  } as any).lazy(() =>
    import('./routes/_protected._management.product-attributes.lazy').then(
      (d) => d.Route,
    ),
  )
const ProtectedManagementOutletandgudangRoute =
  ProtectedManagementOutletandgudangRouteImport.update({
    id: '/outletandgudang',
    path: '/outletandgudang',
    getParentRoute: () => ProtectedManagementRoute,
  } as any).lazy(() =>
    import('./routes/_protected._management.outletandgudang.lazy').then(
      (d) => d.Route,
    ),
  )
const ProtectedInventory_groupMarketsRoute =
  ProtectedInventory_groupMarketsRouteImport.update({
    id: '/markets',
    path: '/markets',
    getParentRoute: () => ProtectedInventory_groupRoute,
  } as any)
const ProtectedInventory_groupInventoryStockRoute =
  ProtectedInventory_groupInventoryStockRouteImport.update({
    id: '/inventory-stock',
    path: '/inventory-stock',
    getParentRoute: () => ProtectedInventory_groupRoute,
  } as any)
const ProtectedInventory_groupInventoryOpsRoute =
  ProtectedInventory_groupInventoryOpsRouteImport.update({
    id: '/inventory-ops',
    path: '/inventory-ops',
    getParentRoute: () => ProtectedInventory_groupRoute,
  } as any)
const ProtectedInventory_groupInventoryRoute =
  ProtectedInventory_groupInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => ProtectedInventory_groupRoute,
  } as any)
const ProtectedInventory_groupInventoryIndexRoute =
  ProtectedInventory_groupInventoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedInventory_groupInventoryRoute,
  } as any)
const ProtectedInventory_groupInventoryRejectRequestsRoute =
  ProtectedInventory_groupInventoryRejectRequestsRouteImport.update({
    id: '/reject-requests',
    path: '/reject-requests',
    getParentRoute: () => ProtectedInventory_groupInventoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof GuestIndexLazyRoute
  '/design': typeof DesignLazyRoute
  '/forbidden': typeof ProtectedForbiddenRoute
  '/kelolagudang': typeof ProtectedKelolagudangRouteWithChildren
  '/kelolaoutlet': typeof ProtectedKelolaoutletRouteWithChildren
  '/pos': typeof ProtectedPosRoute
  '/dashboard': typeof ProtectedDashboardLazyRoute
  '/data-transaksi': typeof ProtectedDataTransaksiLazyRoute
  '/settings': typeof ProtectedSettingsLazyRoute
  '/test-remote-serial': typeof ProtectedTestRemoteSerialLazyRoute
  '/transactions': typeof ProtectedTransactionsLazyRoute
  '/inventory': typeof ProtectedInventory_groupInventoryRouteWithChildren
  '/inventory-ops': typeof ProtectedInventory_groupInventoryOpsRoute
  '/inventory-stock': typeof ProtectedInventory_groupInventoryStockRoute
  '/markets': typeof ProtectedInventory_groupMarketsRoute
  '/outletandgudang': typeof ProtectedManagementOutletandgudangRoute
  '/product-attributes': typeof ProtectedManagementProductAttributesRoute
  '/products': typeof ProtectedManagementProductsRoute
  '/roles': typeof ProtectedManagementRolesRoute
  '/suppliers': typeof ProtectedManagementSuppliersRoute
  '/users': typeof ProtectedManagementUsersRoute
  '/inventory-dashboard': typeof ProtectedInventory_groupInventoryDashboardLazyRoute
  '/stock-management': typeof ProtectedInventory_groupStockManagementLazyRoute
  '/stock-opname': typeof ProtectedInventory_groupStockOpnameLazyRoute
  '/report-item': typeof ProtectedManagementReportItemLazyRoute
  '/kelolagudang/purchases': typeof ProtectedKelolagudangPurchasesLazyRoute
  '/kelolagudang/receive': typeof ProtectedKelolagudangReceiveLazyRoute
  '/kelolagudang/rejects': typeof ProtectedKelolagudangRejectsLazyRoute
  '/kelolagudang/stock': typeof ProtectedKelolagudangStockLazyRoute
  '/kelolagudang/transfers': typeof ProtectedKelolagudangTransfersLazyRoute
  '/kelolaoutlet/receive': typeof ProtectedKelolaoutletReceiveLazyRoute
  '/kelolaoutlet/rejects': typeof ProtectedKelolaoutletRejectsLazyRoute
  '/kelolaoutlet/stock': typeof ProtectedKelolaoutletStockLazyRoute
  '/kelolaoutlet/transfers': typeof ProtectedKelolaoutletTransfersLazyRoute
  '/inventory/reject-requests': typeof ProtectedInventory_groupInventoryRejectRequestsRoute
  '/inventory/': typeof ProtectedInventory_groupInventoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof GuestIndexLazyRoute
  '/design': typeof DesignLazyRoute
  '/forbidden': typeof ProtectedForbiddenRoute
  '/kelolagudang': typeof ProtectedKelolagudangRouteWithChildren
  '/kelolaoutlet': typeof ProtectedKelolaoutletRouteWithChildren
  '/pos': typeof ProtectedPosRoute
  '/dashboard': typeof ProtectedDashboardLazyRoute
  '/data-transaksi': typeof ProtectedDataTransaksiLazyRoute
  '/settings': typeof ProtectedSettingsLazyRoute
  '/test-remote-serial': typeof ProtectedTestRemoteSerialLazyRoute
  '/transactions': typeof ProtectedTransactionsLazyRoute
  '/inventory-ops': typeof ProtectedInventory_groupInventoryOpsRoute
  '/inventory-stock': typeof ProtectedInventory_groupInventoryStockRoute
  '/markets': typeof ProtectedInventory_groupMarketsRoute
  '/outletandgudang': typeof ProtectedManagementOutletandgudangRoute
  '/product-attributes': typeof ProtectedManagementProductAttributesRoute
  '/products': typeof ProtectedManagementProductsRoute
  '/roles': typeof ProtectedManagementRolesRoute
  '/suppliers': typeof ProtectedManagementSuppliersRoute
  '/users': typeof ProtectedManagementUsersRoute
  '/inventory-dashboard': typeof ProtectedInventory_groupInventoryDashboardLazyRoute
  '/stock-management': typeof ProtectedInventory_groupStockManagementLazyRoute
  '/stock-opname': typeof ProtectedInventory_groupStockOpnameLazyRoute
  '/report-item': typeof ProtectedManagementReportItemLazyRoute
  '/kelolagudang/purchases': typeof ProtectedKelolagudangPurchasesLazyRoute
  '/kelolagudang/receive': typeof ProtectedKelolagudangReceiveLazyRoute
  '/kelolagudang/rejects': typeof ProtectedKelolagudangRejectsLazyRoute
  '/kelolagudang/stock': typeof ProtectedKelolagudangStockLazyRoute
  '/kelolagudang/transfers': typeof ProtectedKelolagudangTransfersLazyRoute
  '/kelolaoutlet/receive': typeof ProtectedKelolaoutletReceiveLazyRoute
  '/kelolaoutlet/rejects': typeof ProtectedKelolaoutletRejectsLazyRoute
  '/kelolaoutlet/stock': typeof ProtectedKelolaoutletStockLazyRoute
  '/kelolaoutlet/transfers': typeof ProtectedKelolaoutletTransfersLazyRoute
  '/inventory/reject-requests': typeof ProtectedInventory_groupInventoryRejectRequestsRoute
  '/inventory': typeof ProtectedInventory_groupInventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_guest': typeof GuestRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/design': typeof DesignLazyRoute
  '/_protected/_inventory_group': typeof ProtectedInventory_groupRouteWithChildren
  '/_protected/_management': typeof ProtectedManagementRouteWithChildren
  '/_protected/forbidden': typeof ProtectedForbiddenRoute
  '/_protected/kelolagudang': typeof ProtectedKelolagudangRouteWithChildren
  '/_protected/kelolaoutlet': typeof ProtectedKelolaoutletRouteWithChildren
  '/_protected/pos': typeof ProtectedPosRoute
  '/_protected/dashboard': typeof ProtectedDashboardLazyRoute
  '/_protected/data-transaksi': typeof ProtectedDataTransaksiLazyRoute
  '/_protected/settings': typeof ProtectedSettingsLazyRoute
  '/_protected/test-remote-serial': typeof ProtectedTestRemoteSerialLazyRoute
  '/_protected/transactions': typeof ProtectedTransactionsLazyRoute
  '/_guest/': typeof GuestIndexLazyRoute
  '/_protected/_inventory_group/inventory': typeof ProtectedInventory_groupInventoryRouteWithChildren
  '/_protected/_inventory_group/inventory-ops': typeof ProtectedInventory_groupInventoryOpsRoute
  '/_protected/_inventory_group/inventory-stock': typeof ProtectedInventory_groupInventoryStockRoute
  '/_protected/_inventory_group/markets': typeof ProtectedInventory_groupMarketsRoute
  '/_protected/_management/outletandgudang': typeof ProtectedManagementOutletandgudangRoute
  '/_protected/_management/product-attributes': typeof ProtectedManagementProductAttributesRoute
  '/_protected/_management/products': typeof ProtectedManagementProductsRoute
  '/_protected/_management/roles': typeof ProtectedManagementRolesRoute
  '/_protected/_management/suppliers': typeof ProtectedManagementSuppliersRoute
  '/_protected/_management/users': typeof ProtectedManagementUsersRoute
  '/_protected/_inventory_group/inventory-dashboard': typeof ProtectedInventory_groupInventoryDashboardLazyRoute
  '/_protected/_inventory_group/stock-management': typeof ProtectedInventory_groupStockManagementLazyRoute
  '/_protected/_inventory_group/stock-opname': typeof ProtectedInventory_groupStockOpnameLazyRoute
  '/_protected/_management/report-item': typeof ProtectedManagementReportItemLazyRoute
  '/_protected/kelolagudang/purchases': typeof ProtectedKelolagudangPurchasesLazyRoute
  '/_protected/kelolagudang/receive': typeof ProtectedKelolagudangReceiveLazyRoute
  '/_protected/kelolagudang/rejects': typeof ProtectedKelolagudangRejectsLazyRoute
  '/_protected/kelolagudang/stock': typeof ProtectedKelolagudangStockLazyRoute
  '/_protected/kelolagudang/transfers': typeof ProtectedKelolagudangTransfersLazyRoute
  '/_protected/kelolaoutlet/receive': typeof ProtectedKelolaoutletReceiveLazyRoute
  '/_protected/kelolaoutlet/rejects': typeof ProtectedKelolaoutletRejectsLazyRoute
  '/_protected/kelolaoutlet/stock': typeof ProtectedKelolaoutletStockLazyRoute
  '/_protected/kelolaoutlet/transfers': typeof ProtectedKelolaoutletTransfersLazyRoute
  '/_protected/_inventory_group/inventory/reject-requests': typeof ProtectedInventory_groupInventoryRejectRequestsRoute
  '/_protected/_inventory_group/inventory/': typeof ProtectedInventory_groupInventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/forbidden'
    | '/kelolagudang'
    | '/kelolaoutlet'
    | '/pos'
    | '/dashboard'
    | '/data-transaksi'
    | '/settings'
    | '/test-remote-serial'
    | '/transactions'
    | '/inventory'
    | '/inventory-ops'
    | '/inventory-stock'
    | '/markets'
    | '/outletandgudang'
    | '/product-attributes'
    | '/products'
    | '/roles'
    | '/suppliers'
    | '/users'
    | '/inventory-dashboard'
    | '/stock-management'
    | '/stock-opname'
    | '/report-item'
    | '/kelolagudang/purchases'
    | '/kelolagudang/receive'
    | '/kelolagudang/rejects'
    | '/kelolagudang/stock'
    | '/kelolagudang/transfers'
    | '/kelolaoutlet/receive'
    | '/kelolaoutlet/rejects'
    | '/kelolaoutlet/stock'
    | '/kelolaoutlet/transfers'
    | '/inventory/reject-requests'
    | '/inventory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design'
    | '/forbidden'
    | '/kelolagudang'
    | '/kelolaoutlet'
    | '/pos'
    | '/dashboard'
    | '/data-transaksi'
    | '/settings'
    | '/test-remote-serial'
    | '/transactions'
    | '/inventory-ops'
    | '/inventory-stock'
    | '/markets'
    | '/outletandgudang'
    | '/product-attributes'
    | '/products'
    | '/roles'
    | '/suppliers'
    | '/users'
    | '/inventory-dashboard'
    | '/stock-management'
    | '/stock-opname'
    | '/report-item'
    | '/kelolagudang/purchases'
    | '/kelolagudang/receive'
    | '/kelolagudang/rejects'
    | '/kelolagudang/stock'
    | '/kelolagudang/transfers'
    | '/kelolaoutlet/receive'
    | '/kelolaoutlet/rejects'
    | '/kelolaoutlet/stock'
    | '/kelolaoutlet/transfers'
    | '/inventory/reject-requests'
    | '/inventory'
  id:
    | '__root__'
    | '/_guest'
    | '/_protected'
    | '/design'
    | '/_protected/_inventory_group'
    | '/_protected/_management'
    | '/_protected/forbidden'
    | '/_protected/kelolagudang'
    | '/_protected/kelolaoutlet'
    | '/_protected/pos'
    | '/_protected/dashboard'
    | '/_protected/data-transaksi'
    | '/_protected/settings'
    | '/_protected/test-remote-serial'
    | '/_protected/transactions'
    | '/_guest/'
    | '/_protected/_inventory_group/inventory'
    | '/_protected/_inventory_group/inventory-ops'
    | '/_protected/_inventory_group/inventory-stock'
    | '/_protected/_inventory_group/markets'
    | '/_protected/_management/outletandgudang'
    | '/_protected/_management/product-attributes'
    | '/_protected/_management/products'
    | '/_protected/_management/roles'
    | '/_protected/_management/suppliers'
    | '/_protected/_management/users'
    | '/_protected/_inventory_group/inventory-dashboard'
    | '/_protected/_inventory_group/stock-management'
    | '/_protected/_inventory_group/stock-opname'
    | '/_protected/_management/report-item'
    | '/_protected/kelolagudang/purchases'
    | '/_protected/kelolagudang/receive'
    | '/_protected/kelolagudang/rejects'
    | '/_protected/kelolagudang/stock'
    | '/_protected/kelolagudang/transfers'
    | '/_protected/kelolaoutlet/receive'
    | '/_protected/kelolaoutlet/rejects'
    | '/_protected/kelolaoutlet/stock'
    | '/_protected/kelolaoutlet/transfers'
    | '/_protected/_inventory_group/inventory/reject-requests'
    | '/_protected/_inventory_group/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GuestRoute: typeof GuestRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  DesignLazyRoute: typeof DesignLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/': {
      id: '/_guest/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GuestIndexLazyRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_protected/transactions': {
      id: '/_protected/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof ProtectedTransactionsLazyRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/test-remote-serial': {
      id: '/_protected/test-remote-serial'
      path: '/test-remote-serial'
      fullPath: '/test-remote-serial'
      preLoaderRoute: typeof ProtectedTestRemoteSerialLazyRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsLazyRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/data-transaksi': {
      id: '/_protected/data-transaksi'
      path: '/data-transaksi'
      fullPath: '/data-transaksi'
      preLoaderRoute: typeof ProtectedDataTransaksiLazyRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardLazyRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/pos': {
      id: '/_protected/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof ProtectedPosRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/kelolaoutlet': {
      id: '/_protected/kelolaoutlet'
      path: '/kelolaoutlet'
      fullPath: '/kelolaoutlet'
      preLoaderRoute: typeof ProtectedKelolaoutletRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/kelolagudang': {
      id: '/_protected/kelolagudang'
      path: '/kelolagudang'
      fullPath: '/kelolagudang'
      preLoaderRoute: typeof ProtectedKelolagudangRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/forbidden': {
      id: '/_protected/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ProtectedForbiddenRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_management': {
      id: '/_protected/_management'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedManagementRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_inventory_group': {
      id: '/_protected/_inventory_group'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedInventory_groupRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/kelolaoutlet/transfers': {
      id: '/_protected/kelolaoutlet/transfers'
      path: '/transfers'
      fullPath: '/kelolaoutlet/transfers'
      preLoaderRoute: typeof ProtectedKelolaoutletTransfersLazyRouteImport
      parentRoute: typeof ProtectedKelolaoutletRoute
    }
    '/_protected/kelolaoutlet/stock': {
      id: '/_protected/kelolaoutlet/stock'
      path: '/stock'
      fullPath: '/kelolaoutlet/stock'
      preLoaderRoute: typeof ProtectedKelolaoutletStockLazyRouteImport
      parentRoute: typeof ProtectedKelolaoutletRoute
    }
    '/_protected/kelolaoutlet/rejects': {
      id: '/_protected/kelolaoutlet/rejects'
      path: '/rejects'
      fullPath: '/kelolaoutlet/rejects'
      preLoaderRoute: typeof ProtectedKelolaoutletRejectsLazyRouteImport
      parentRoute: typeof ProtectedKelolaoutletRoute
    }
    '/_protected/kelolaoutlet/receive': {
      id: '/_protected/kelolaoutlet/receive'
      path: '/receive'
      fullPath: '/kelolaoutlet/receive'
      preLoaderRoute: typeof ProtectedKelolaoutletReceiveLazyRouteImport
      parentRoute: typeof ProtectedKelolaoutletRoute
    }
    '/_protected/kelolagudang/transfers': {
      id: '/_protected/kelolagudang/transfers'
      path: '/transfers'
      fullPath: '/kelolagudang/transfers'
      preLoaderRoute: typeof ProtectedKelolagudangTransfersLazyRouteImport
      parentRoute: typeof ProtectedKelolagudangRoute
    }
    '/_protected/kelolagudang/stock': {
      id: '/_protected/kelolagudang/stock'
      path: '/stock'
      fullPath: '/kelolagudang/stock'
      preLoaderRoute: typeof ProtectedKelolagudangStockLazyRouteImport
      parentRoute: typeof ProtectedKelolagudangRoute
    }
    '/_protected/kelolagudang/rejects': {
      id: '/_protected/kelolagudang/rejects'
      path: '/rejects'
      fullPath: '/kelolagudang/rejects'
      preLoaderRoute: typeof ProtectedKelolagudangRejectsLazyRouteImport
      parentRoute: typeof ProtectedKelolagudangRoute
    }
    '/_protected/kelolagudang/receive': {
      id: '/_protected/kelolagudang/receive'
      path: '/receive'
      fullPath: '/kelolagudang/receive'
      preLoaderRoute: typeof ProtectedKelolagudangReceiveLazyRouteImport
      parentRoute: typeof ProtectedKelolagudangRoute
    }
    '/_protected/kelolagudang/purchases': {
      id: '/_protected/kelolagudang/purchases'
      path: '/purchases'
      fullPath: '/kelolagudang/purchases'
      preLoaderRoute: typeof ProtectedKelolagudangPurchasesLazyRouteImport
      parentRoute: typeof ProtectedKelolagudangRoute
    }
    '/_protected/_management/report-item': {
      id: '/_protected/_management/report-item'
      path: '/report-item'
      fullPath: '/report-item'
      preLoaderRoute: typeof ProtectedManagementReportItemLazyRouteImport
      parentRoute: typeof ProtectedManagementRoute
    }
    '/_protected/_inventory_group/stock-opname': {
      id: '/_protected/_inventory_group/stock-opname'
      path: '/stock-opname'
      fullPath: '/stock-opname'
      preLoaderRoute: typeof ProtectedInventory_groupStockOpnameLazyRouteImport
      parentRoute: typeof ProtectedInventory_groupRoute
    }
    '/_protected/_inventory_group/stock-management': {
      id: '/_protected/_inventory_group/stock-management'
      path: '/stock-management'
      fullPath: '/stock-management'
      preLoaderRoute: typeof ProtectedInventory_groupStockManagementLazyRouteImport
      parentRoute: typeof ProtectedInventory_groupRoute
    }
    '/_protected/_inventory_group/inventory-dashboard': {
      id: '/_protected/_inventory_group/inventory-dashboard'
      path: '/inventory-dashboard'
      fullPath: '/inventory-dashboard'
      preLoaderRoute: typeof ProtectedInventory_groupInventoryDashboardLazyRouteImport
      parentRoute: typeof ProtectedInventory_groupRoute
    }
    '/_protected/_management/users': {
      id: '/_protected/_management/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ProtectedManagementUsersRouteImport
      parentRoute: typeof ProtectedManagementRoute
    }
    '/_protected/_management/suppliers': {
      id: '/_protected/_management/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof ProtectedManagementSuppliersRouteImport
      parentRoute: typeof ProtectedManagementRoute
    }
    '/_protected/_management/roles': {
      id: '/_protected/_management/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof ProtectedManagementRolesRouteImport
      parentRoute: typeof ProtectedManagementRoute
    }
    '/_protected/_management/products': {
      id: '/_protected/_management/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProtectedManagementProductsRouteImport
      parentRoute: typeof ProtectedManagementRoute
    }
    '/_protected/_management/product-attributes': {
      id: '/_protected/_management/product-attributes'
      path: '/product-attributes'
      fullPath: '/product-attributes'
      preLoaderRoute: typeof ProtectedManagementProductAttributesRouteImport
      parentRoute: typeof ProtectedManagementRoute
    }
    '/_protected/_management/outletandgudang': {
      id: '/_protected/_management/outletandgudang'
      path: '/outletandgudang'
      fullPath: '/outletandgudang'
      preLoaderRoute: typeof ProtectedManagementOutletandgudangRouteImport
      parentRoute: typeof ProtectedManagementRoute
    }
    '/_protected/_inventory_group/markets': {
      id: '/_protected/_inventory_group/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof ProtectedInventory_groupMarketsRouteImport
      parentRoute: typeof ProtectedInventory_groupRoute
    }
    '/_protected/_inventory_group/inventory-stock': {
      id: '/_protected/_inventory_group/inventory-stock'
      path: '/inventory-stock'
      fullPath: '/inventory-stock'
      preLoaderRoute: typeof ProtectedInventory_groupInventoryStockRouteImport
      parentRoute: typeof ProtectedInventory_groupRoute
    }
    '/_protected/_inventory_group/inventory-ops': {
      id: '/_protected/_inventory_group/inventory-ops'
      path: '/inventory-ops'
      fullPath: '/inventory-ops'
      preLoaderRoute: typeof ProtectedInventory_groupInventoryOpsRouteImport
      parentRoute: typeof ProtectedInventory_groupRoute
    }
    '/_protected/_inventory_group/inventory': {
      id: '/_protected/_inventory_group/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof ProtectedInventory_groupInventoryRouteImport
      parentRoute: typeof ProtectedInventory_groupRoute
    }
    '/_protected/_inventory_group/inventory/': {
      id: '/_protected/_inventory_group/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof ProtectedInventory_groupInventoryIndexRouteImport
      parentRoute: typeof ProtectedInventory_groupInventoryRoute
    }
    '/_protected/_inventory_group/inventory/reject-requests': {
      id: '/_protected/_inventory_group/inventory/reject-requests'
      path: '/reject-requests'
      fullPath: '/inventory/reject-requests'
      preLoaderRoute: typeof ProtectedInventory_groupInventoryRejectRequestsRouteImport
      parentRoute: typeof ProtectedInventory_groupInventoryRoute
    }
  }
}

interface GuestRouteChildren {
  GuestIndexLazyRoute: typeof GuestIndexLazyRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestIndexLazyRoute: GuestIndexLazyRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

interface ProtectedInventory_groupInventoryRouteChildren {
  ProtectedInventory_groupInventoryRejectRequestsRoute: typeof ProtectedInventory_groupInventoryRejectRequestsRoute
  ProtectedInventory_groupInventoryIndexRoute: typeof ProtectedInventory_groupInventoryIndexRoute
}

const ProtectedInventory_groupInventoryRouteChildren: ProtectedInventory_groupInventoryRouteChildren =
  {
    ProtectedInventory_groupInventoryRejectRequestsRoute:
      ProtectedInventory_groupInventoryRejectRequestsRoute,
    ProtectedInventory_groupInventoryIndexRoute:
      ProtectedInventory_groupInventoryIndexRoute,
  }

const ProtectedInventory_groupInventoryRouteWithChildren =
  ProtectedInventory_groupInventoryRoute._addFileChildren(
    ProtectedInventory_groupInventoryRouteChildren,
  )

interface ProtectedInventory_groupRouteChildren {
  ProtectedInventory_groupInventoryRoute: typeof ProtectedInventory_groupInventoryRouteWithChildren
  ProtectedInventory_groupInventoryOpsRoute: typeof ProtectedInventory_groupInventoryOpsRoute
  ProtectedInventory_groupInventoryStockRoute: typeof ProtectedInventory_groupInventoryStockRoute
  ProtectedInventory_groupMarketsRoute: typeof ProtectedInventory_groupMarketsRoute
  ProtectedInventory_groupInventoryDashboardLazyRoute: typeof ProtectedInventory_groupInventoryDashboardLazyRoute
  ProtectedInventory_groupStockManagementLazyRoute: typeof ProtectedInventory_groupStockManagementLazyRoute
  ProtectedInventory_groupStockOpnameLazyRoute: typeof ProtectedInventory_groupStockOpnameLazyRoute
}

const ProtectedInventory_groupRouteChildren: ProtectedInventory_groupRouteChildren =
  {
    ProtectedInventory_groupInventoryRoute:
      ProtectedInventory_groupInventoryRouteWithChildren,
    ProtectedInventory_groupInventoryOpsRoute:
      ProtectedInventory_groupInventoryOpsRoute,
    ProtectedInventory_groupInventoryStockRoute:
      ProtectedInventory_groupInventoryStockRoute,
    ProtectedInventory_groupMarketsRoute: ProtectedInventory_groupMarketsRoute,
    ProtectedInventory_groupInventoryDashboardLazyRoute:
      ProtectedInventory_groupInventoryDashboardLazyRoute,
    ProtectedInventory_groupStockManagementLazyRoute:
      ProtectedInventory_groupStockManagementLazyRoute,
    ProtectedInventory_groupStockOpnameLazyRoute:
      ProtectedInventory_groupStockOpnameLazyRoute,
  }

const ProtectedInventory_groupRouteWithChildren =
  ProtectedInventory_groupRoute._addFileChildren(
    ProtectedInventory_groupRouteChildren,
  )

interface ProtectedManagementRouteChildren {
  ProtectedManagementOutletandgudangRoute: typeof ProtectedManagementOutletandgudangRoute
  ProtectedManagementProductAttributesRoute: typeof ProtectedManagementProductAttributesRoute
  ProtectedManagementProductsRoute: typeof ProtectedManagementProductsRoute
  ProtectedManagementRolesRoute: typeof ProtectedManagementRolesRoute
  ProtectedManagementSuppliersRoute: typeof ProtectedManagementSuppliersRoute
  ProtectedManagementUsersRoute: typeof ProtectedManagementUsersRoute
  ProtectedManagementReportItemLazyRoute: typeof ProtectedManagementReportItemLazyRoute
}

const ProtectedManagementRouteChildren: ProtectedManagementRouteChildren = {
  ProtectedManagementOutletandgudangRoute:
    ProtectedManagementOutletandgudangRoute,
  ProtectedManagementProductAttributesRoute:
    ProtectedManagementProductAttributesRoute,
  ProtectedManagementProductsRoute: ProtectedManagementProductsRoute,
  ProtectedManagementRolesRoute: ProtectedManagementRolesRoute,
  ProtectedManagementSuppliersRoute: ProtectedManagementSuppliersRoute,
  ProtectedManagementUsersRoute: ProtectedManagementUsersRoute,
  ProtectedManagementReportItemLazyRoute:
    ProtectedManagementReportItemLazyRoute,
}

const ProtectedManagementRouteWithChildren =
  ProtectedManagementRoute._addFileChildren(ProtectedManagementRouteChildren)

interface ProtectedKelolagudangRouteChildren {
  ProtectedKelolagudangPurchasesLazyRoute: typeof ProtectedKelolagudangPurchasesLazyRoute
  ProtectedKelolagudangReceiveLazyRoute: typeof ProtectedKelolagudangReceiveLazyRoute
  ProtectedKelolagudangRejectsLazyRoute: typeof ProtectedKelolagudangRejectsLazyRoute
  ProtectedKelolagudangStockLazyRoute: typeof ProtectedKelolagudangStockLazyRoute
  ProtectedKelolagudangTransfersLazyRoute: typeof ProtectedKelolagudangTransfersLazyRoute
}

const ProtectedKelolagudangRouteChildren: ProtectedKelolagudangRouteChildren = {
  ProtectedKelolagudangPurchasesLazyRoute:
    ProtectedKelolagudangPurchasesLazyRoute,
  ProtectedKelolagudangReceiveLazyRoute: ProtectedKelolagudangReceiveLazyRoute,
  ProtectedKelolagudangRejectsLazyRoute: ProtectedKelolagudangRejectsLazyRoute,
  ProtectedKelolagudangStockLazyRoute: ProtectedKelolagudangStockLazyRoute,
  ProtectedKelolagudangTransfersLazyRoute:
    ProtectedKelolagudangTransfersLazyRoute,
}

const ProtectedKelolagudangRouteWithChildren =
  ProtectedKelolagudangRoute._addFileChildren(
    ProtectedKelolagudangRouteChildren,
  )

interface ProtectedKelolaoutletRouteChildren {
  ProtectedKelolaoutletReceiveLazyRoute: typeof ProtectedKelolaoutletReceiveLazyRoute
  ProtectedKelolaoutletRejectsLazyRoute: typeof ProtectedKelolaoutletRejectsLazyRoute
  ProtectedKelolaoutletStockLazyRoute: typeof ProtectedKelolaoutletStockLazyRoute
  ProtectedKelolaoutletTransfersLazyRoute: typeof ProtectedKelolaoutletTransfersLazyRoute
}

const ProtectedKelolaoutletRouteChildren: ProtectedKelolaoutletRouteChildren = {
  ProtectedKelolaoutletReceiveLazyRoute: ProtectedKelolaoutletReceiveLazyRoute,
  ProtectedKelolaoutletRejectsLazyRoute: ProtectedKelolaoutletRejectsLazyRoute,
  ProtectedKelolaoutletStockLazyRoute: ProtectedKelolaoutletStockLazyRoute,
  ProtectedKelolaoutletTransfersLazyRoute:
    ProtectedKelolaoutletTransfersLazyRoute,
}

const ProtectedKelolaoutletRouteWithChildren =
  ProtectedKelolaoutletRoute._addFileChildren(
    ProtectedKelolaoutletRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedInventory_groupRoute: typeof ProtectedInventory_groupRouteWithChildren
  ProtectedManagementRoute: typeof ProtectedManagementRouteWithChildren
  ProtectedForbiddenRoute: typeof ProtectedForbiddenRoute
  ProtectedKelolagudangRoute: typeof ProtectedKelolagudangRouteWithChildren
  ProtectedKelolaoutletRoute: typeof ProtectedKelolaoutletRouteWithChildren
  ProtectedPosRoute: typeof ProtectedPosRoute
  ProtectedDashboardLazyRoute: typeof ProtectedDashboardLazyRoute
  ProtectedDataTransaksiLazyRoute: typeof ProtectedDataTransaksiLazyRoute
  ProtectedSettingsLazyRoute: typeof ProtectedSettingsLazyRoute
  ProtectedTestRemoteSerialLazyRoute: typeof ProtectedTestRemoteSerialLazyRoute
  ProtectedTransactionsLazyRoute: typeof ProtectedTransactionsLazyRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedInventory_groupRoute: ProtectedInventory_groupRouteWithChildren,
  ProtectedManagementRoute: ProtectedManagementRouteWithChildren,
  ProtectedForbiddenRoute: ProtectedForbiddenRoute,
  ProtectedKelolagudangRoute: ProtectedKelolagudangRouteWithChildren,
  ProtectedKelolaoutletRoute: ProtectedKelolaoutletRouteWithChildren,
  ProtectedPosRoute: ProtectedPosRoute,
  ProtectedDashboardLazyRoute: ProtectedDashboardLazyRoute,
  ProtectedDataTransaksiLazyRoute: ProtectedDataTransaksiLazyRoute,
  ProtectedSettingsLazyRoute: ProtectedSettingsLazyRoute,
  ProtectedTestRemoteSerialLazyRoute: ProtectedTestRemoteSerialLazyRoute,
  ProtectedTransactionsLazyRoute: ProtectedTransactionsLazyRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  GuestRoute: GuestRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  DesignLazyRoute: DesignLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
